name: Monthly Archive Downloads

on:
  schedule:
    # 台北 00:10 (UTC+8) = 前一日 16:10 UTC；設定每月 1 日 16:10 UTC
    - cron: '10 16 1 * *'
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: monthly-archive
  cancel-in-progress: false

jobs:
  archive:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Taipei
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # 讓 GITHUB_TOKEN 可 push

      - name: Prepare archive folder & copy files
        run: |
          set -e
          MONTH=$(date +'%Y-%m')
          TARGET="archive/${MONTH}"
          mkdir -p "$TARGET"
          echo "[archive] target = $TARGET"

          # 若 downloads 目錄不存在或沒有 xlsx，則跳過
          if [ ! -d downloads ]; then
            echo "[archive] skip: downloads/ not found"
            exit 0
          fi

          XLSX_COUNT=$(ls -1 downloads/*.xlsx 2>/dev/null | wc -l | tr -d ' ')
          if [ "$XLSX_COUNT" = "0" ]; then
            echo "[archive] skip: no xlsx in downloads/"
            exit 0
          fi

          cp -f downloads/*.xlsx "$TARGET"/
          echo "[archive] copied $XLSX_COUNT files to $TARGET"

      - name: Commit & push
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add archive/
          if git diff --cached --quiet; then
            echo "[archive] nothing to commit."
            exit 0
          fi

          git commit -m "Archive downloads xlsx for $(date +'%Y-%m')"
          git push
