name: Daily Fetch (00981A raw snapshot)
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Asia/Taipei
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install minimal deps
        run: |
          python -m pip install -U pip
          pip install selenium pandas openpyxl chromedriver-autoinstaller matplotlib requests
      - name: Run fetcher (download -> with_prices -> csv)
        run: python etf_tracker.py
      - name: Commit & push (raw + dedup snapshot)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/ archive/ manifest/ data_snapshots/ prices/ || true
          git diff --cached --quiet || git commit -m "Daily raw snapshot: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push
      - name: Upload screenshots (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/
          if-no-files-found: ignore
